{
 "title": "IAM Role Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "iam_role",
    "query": {
     "query": "label_values(aws_total_cost_by_iam_role,role_arn)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IAM Roles Total Cost",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_total_cost_by_iam_role{role_arn=~\"$iam_role\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IAM Role Cost by Lambda",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_lambda_cost_by_iam_role{role_arn=~\"$iam_role\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IAM Role Cost by Cloudwatch",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_cloudwatch_cost_by_iam_role{role_arn=~\"$iam_role\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IAM Role Cost by SNS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_sns_cost_by_iam_role{role_arn=~\"$iam_role\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}